const f = () => {

    try {
        let a = 0;
        nalio = uore;
        console.log("Program ran successfully");
    } catch (error) {
        console.log("This is an error");
        console.log(p);
    } finally {
        console.log("I am a good boy...")
    }

}
f();
console.log("HELLO...");